# docker-compose.yml
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - library-network
    ports:
      - "5444:5432"

  backend:
    build: ./backend
    command: bash -c "./wait-for-db.sh && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles  # Постоянное хранилище для статики
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - library-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - library-network

volumes:
  postgres_data:
  static_volume:

networks:
  library-network:
    driver: bridge